### PR TITLE
feat: add French and Dutch translations

### PR DESCRIPTION
**Pull request by m3ftah**
This adds French and Dutch translations for the ui, such as the Universe selector, the language selector and the search placeholder.

### CODE REVIEW

**Comment by MGasztold** [comment]
@m3ftah  Hello, Could you please tell me how to switch to using French translation? I have tried 

```
val opts = MapOptions.Builder()
            .centerOnVenue("{my_id}")
            .language(Locale.FRANCE.language)
            .build()
```

but it did not work.

**Comment by MGasztold** [comment]
@m3ftah  Hello, Could you tell me how can I use French translation in my app? I have tried 

```
val opts = MapOptions.Builder()
            .centerOnVenue("{my_id}")
            .language(Locale.FRANCE.language)
            .build()
```

but there is still english inside the fragment and searchbar.

**Comment by m3ftah** [comment]
Hello @MGasztold, the `fragment` and `searchbar` label languages are based on the Phone Locales, please try changing the language of your device.

**Comment by MGasztold** [comment]
@m3ftah  Ok, it works. Thank you.

**Pull request merged**
