### PR TITLE
Map displaying bubbles for floors to the right even when there's only one floor

### PR DESCRIPTION
**Pull request by astamato**
Issue #4 suggested feature impl

### CODE REVIEW

**Comment by emerciercontexeo** [comment]
Thanks @astamato for this PR

Some developers ask to hide the floor controller if only one floor is displayed but others want to display it. For example, if you have one floor place but it is the floor 17, you may want to display it.

In my opinion, we should add a method to the UIBehaviour interface to let developer hide or show the floor controller dnamically.

```java
public interface UIBehaviour {
     boolean shouldDisplayInformationButton(MapwizeObject mapwizeObject);
++boolean shouldDisplayFloorController(List<Double> floors);
}
```

Does this sound good to you?

**Comment by astamato** [comment]
You're absolutely correct it should be configurable. I can work into adding that bit as part of this PR.

**Comment by emerciercontexeo** [comment]
Thanks @astamato 

I will create a PR in few minutes so do not lose time with this :)

**Comment by astamato** [comment]
Oh I'm sorry we already have this feature implemented in MapwizeFragmentUISettings, its property floorControllerHidden. Thanks for your support I'm closing this PR.

**Pull request closed without merging**
